name: TeamCity Tests

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Install Docker
        run: sudo apt-get install docker-ce docker-ce-cli containerd.io

      - name: Install Docker Compose
        run: sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && sudo chmod +x /usr/local/bin/docker-compose

      - name: Request IP
        run: |
          export ips=$(ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1')
          export ip=${ips%%$'\n'*}
          echo "Current IP: $ip"

      - name: Delete previous run data
        run: |
          cd infra
          rm -rf teamcity_tests_infrastructure
          mkdir teamcity_tests_infrastructure
          cd teamcity_tests_infrastructure
          for dir in teamcity_server teamcity_agent selenoid; do
            mkdir $dir
          done
          for container in teamcity_server_instance teamcity_agent_instance selenoid_instance selenoid_ui_instance; do
            docker stop $container || true
            docker rm $container || true
          done

      - name: Start teamcity server
        run: |
          cd infra/teamcity_tests_infrastructure/teamcity_server
          docker run -d --name teamcity_server_instance  \
            -v $(pwd)/logs:/opt/teamcity/logs  \
            -p 8111:8111 \
            jetbrains/teamcity-server

      - name: Start selenoid
        run: |
          cd infra/teamcity_tests_infrastructure/selenoid
          mkdir config
          cp ../../../infra/browsers.json config/
          docker run -d --name selenoid_instance \
            -p 4444:4444 \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v $(pwd)/config/:/etc/selenoid/:ro \
            aerokube/selenoid:latest-release
          image_names=($(awk -F'"' '/"image": "/{print $4}' config/browsers.json))
          for image in "${image_names[@]}"; do
            docker pull $image
          done

      - name: Start selenoid-ui
        run: |
          docker run -d --platform linux/amd64 --name selenoid_ui_instance \
            -p 8080:8080 aerokube/selenoid-ui --selenoid-uri "http://$ip:4444"

      - name: Setup teamcity server
        run: |
          echo -e "host=$ip:8111\nremote=http://$ip:4444/wd/hub\nbrowser=chrome\nmaxRetryCount=0" > src/main/resources/config.properties  
          cat src/main/resources/config.properties
          mvn clean test -Dtest=SetupFirstStartTest#startUpTest

      - name: Parse superuser token
        run: |
          superuser_token=$(grep -o 'Super user authentication token: [0-9]*' infra/teamcity_tests_infrastructure/teamcity_server/logs/teamcity-server.log | awk '{print $NF}')
          echo "Super user token: $superuser_token"
          echo "##[set-output name=superuser_token;]$superuser_token"

      - name: Start teamcity agent
        run: |
          cd infra/teamcity_tests_infrastructure/teamcity_agent
          mkdir conf
          docker run -e SERVER_URL=http://$ip:8111 -u 0 -d --name teamcity_agent_instance \
            -v $(pwd)/conf:/data/teamcity_agent/conf \
            jetbrains/teamcity-agent:2023.11.1

      - name: Run system tests
        run: |
          echo -e "superUserToken=${{ steps.parse_superuser_token.outputs.superuser_token }}" > src/main/resources/config.properties
          cat src/main/resources/config.properties
          mvn clean test -Dtest=SetupFirstStartTest#setupTeamCityAgentTest

      - name: Run API tests
        run: mvn test -DsuiteXmlFile=testng-suites/api-suite.xml

      - name: Run UI tests
        run: mvn test -DsuiteXmlFile=testng-suites/ui-suite.xml